version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt-get update
      - apt-get install imagemagick -y
  build:
    commands:
      #
      # Building the site using Avocado.
      #
      - npm run build
  post_build:
    commands:
      - ./node_modules/.bin/potato -s _output -u -b $S3_BUCKET